### ISSUE TITLE
Error in read-me

### ISSUE THREAD

**Issue by b1g1an** [walthowd/ha-alexa-tts#1]
Hi, first off, many thanks for this. TTS was a great addition but this is the icing on the cake.

There is an error in your read me, the command is missing .sh, so should be...

```
notify:
  - platform: command_line
    name: 'My Dot Name'
    command: "/home/homeassistant/.homeassistant/alexa_wrapper.sh -d 'My Dot Name'"
```

and

```
notify:
  - platform: command_line
    name: 'All Alexas'
    command: "/home/homeassistant/.homeassistant/alexa_wrapper.sh -d 'ALL'"
```

You may also like to add a note for hassio users, the command would be…

`    command: "/config/alexa_wrapper.sh -d 'ALL'"`

...but apart from that the install is identical.
