### ISSUE TITLE
Hass.io Implementation Help

### ISSUE THREAD

**Issue by NathanWilcox** [walthowd/ha-alexa-tts#24]
I have followed each step and have successfully managed to test the commands from the command line. 

Since adding to to Hass.io I have tried to make a script call but this doesn't work. I have also tried to make a service call using the following request:

![screen shot 2018-12-05 at 23 24 12](https://user-images.githubusercontent.com/25329410/49550881-fd421b00-f8e4-11e8-8f04-6e6feefcd417.png)

But unfortunately upon every call I get the following error:

> 2018-12-05 23:22:19 ERROR (SyncWorker_15) [homeassistant.components.notify.command_line] Command failed: /config/alexa_wrapper.sh -d 'Nathan's Echo Dot'

I've tried several calls and each time the same thing.

Here's my config.yaml notify:

```
#Notify
notify:
  - platform: command_line
    name: "Livingroom Echo"
    command: "/config/alexa_wrapper.sh -d 'Nathan's Echo Dot'"
```

Here's my PATH:
```
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ALEXA_REMOTE="$DIR/alexa_remote_control.sh"
```

Any help would be greatly appreciated being so close to a result.
